### ISSUE TITLE
Unable to read data from more than 10 rows or columsn

### ISSUE THREAD

**Issue by knreddy036** [sail-sail/read_xlsx#1]
Hi ,

I am using the below code for reading data from excel. when try to retrieve data from the cell (11,0), I am getting an error

 workbook.getSheet("Sheet1").then(function(sheet){
         var rowLen = sheet.getRows();
         var cellLen = sheet.getColumns();
         console.log('rowcount'+rowLen);
         console.log('Cellcount'+cellLen);

               var a=sheet.getCell(11,0);
        console.log(a.getContents());

Thanks,
Nagarjuna

**Comment by sail-sail** [comment]
var cell = sheet.getCell(11,0);
//If the cell is empty, it is possible that the cell does not exist return null!
if(cell != null) {
    console.log(cell.getName()+":"+cell.getContents());
}
